version: '3.1'

services:

  mat-webserver-prod:
    image: mamat08nurahmat/bni_inacraft:prod
    restart: always
    ports:
      - 2222:80
    environment:
      WORDPRESS_DB_HOST: mariadb001.cmeypdk92ow4.us-west-2.rds.amazonaws.com
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: mamat123
      WORDPRESS_DB_NAME: kuesioner
